---
services:
  gitlab:
    hostname: ${GITLAB_HOST}
    container_name: gitlab
    image: gitlab/gitlab-ce
    ports:
      - "8001:80"
      - "2222:22"

    env_file: .env
    volumes:
      - ./config/gitlab:/var/opt/gitlab
      - ./data/gitlab:/etc/gitlab
    restart: unless-stopped

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    network_mode: 'host'
